### ISSUE TITLE
Destroy session on Tab or browser close

### ISSUE THREAD

**Issue by MilovanovMaxim** [MilovanovMaxim/manualBooks#10]
But please be sure when you refresh page you shoud first get right userId and only then ask API

**Comment by SRobertZ** [comment]
Могу написать вот такой код но в этом случае на F5 будет также стераться прфиль+ необходимо реализовывать проверку на наличие данных в локал сторадж и выкидывать на страницу логина если что
angular.element($window).bind("beforeunload", function(){
            profileService.clearProfile();
        })

**Comment by MilovanovMaxim** [comment]
Это не верно, возможно надо хранить в sessionStorage а не в localStorage, главная проблема в том что после рефреша страницы откуда-то вылазит user_id = 0

**Comment by SRobertZ** [comment]
Заменил на sessionStorage. ПРоблему с  user_id = 0 решил еще вчера.
Но надо еще делать проверку на выкидывание пользователя в случае если user_id=0
