### ISSUE TITLE
User_id did not changed after I regiater a new user

### ISSUE THREAD

**Issue by MilovanovMaxim** [MilovanovMaxim/manualBooks#13]
[picture N1](https://yadi.sk/i/XgQR06SYeop9o) I am Maxim mma1@gmail.com 123456
[picture N2](https://yadi.sk/i/1l8GtEgseopCS) I am Max aaa@aaa.aa

Page refresh helps. Need to understand where is the problem, is it our problem or API gives us wrong user ID

**Comment by SRobertZ** [comment]
It's completely my bug.
