### ISSUE TITLE
add posibility to user to remove account

### ISSUE THREAD

**Issue by MilovanovMaxim** [MilovanovMaxim/manualBooks#18]
[screen](https://yadi.sk/i/t3wW8xdbepTeS)
this button will set user status to 0/1 and send this info to the server
post statusUser user_id, status
markUp - should change color
color: red; for off
blue for on

**Comment by SRobertZ** [comment]
Не открывается скриншот- не понимаю что надо сделать

**Comment by MilovanovMaxim** [comment]
Попробуй еще раз, открывается
