### ISSUE TITLE
Проблема с website_id

### ISSUE THREAD

**Issue by MilovanovMaxim** [MilovanovMaxim/manualBooks#26]
столкнулся с такой проблемой
регистрирую пользователя qqqq@qqqq.qq пароль qqqq Client ID = 1234
логинюсь им, мне их гребаное API отдает хрень, но это их проблема,

**Comment by SRobertZ** [comment]
Когда ты делаешь login уходит 1001 по умолчанию, так как нет еще website_id.
Могу вообще не отправлять website_id на login

**Comment by SRobertZ** [comment]
Да бага есть. Поправлю щас
