### ISSUE TITLE
Удаление закладок

### ISSUE THREAD

**Issue by MilovanovMaxim** [MilovanovMaxim/manualBooks#31]
С из того же места где их добавляют их можно удалять, делается также нажатием на пин
вызывается removeBookmark с bookmark_id

**Comment by SRobertZ** [comment]
Для того чтобы удалять по bookmark_id метод displayPages длжен возвращать bookmark_id.
Я сделал removeBookmark и передаю туда pageId- пусть removeBookmark переделает, чтобы принимал pageId
