### ISSUE TITLE
Изменить редактирование профиля

### ISSUE THREAD

**Issue by MilovanovMaxim** [MilovanovMaxim/manualBooks#38]
https://yadi.sk/i/kO3s_4jOewFkK

**Comment by MilovanovMaxim** [comment]
Потом добавить ошибки, когда будет готова разметка
[check email API](https://slack-files.com/T02J7P39U-F03RUNS5S-20a7b209f6)

**Comment by SRobertZ** [comment]
А разметка когда будет?

**Comment by MilovanovMaxim** [comment]
Говорит используйте тоже самое что и для смены аватара

**Comment by SRobertZ** [comment]
Ту же что и для смены пароля ты имел в виду?

**Comment by SRobertZ** [comment]
Сделаю завтра в обед

**Comment by MilovanovMaxim** [comment]
Рави сказал что теперь возвращает поле с ошибкой
