### ISSUE TITLE
Переделать Download page and download version

### ISSUE THREAD

**Issue by MilovanovMaxim** [MilovanovMaxim/manualBooks#39]
https://yadi.sk/i/WNvJRcsGewFny

**Comment by SRobertZ** [comment]
Ravi опять возвращает файл, аместо ссылки. Если файл должен скачиваться пи нажатии, то сервер должен ставить спец заголовки, чтобы браузер понял что пришел файл и предложил сохранить

**Comment by MilovanovMaxim** [comment]
All you do is click on that link and it will  open pdf

**Comment by MilovanovMaxim** [comment]
Говорит не делай скачивание сделай ссылку

**Comment by MilovanovMaxim** [comment]
С таргет _blank
