### ISSUE TITLE
Change Avatar

### ISSUE THREAD

**Issue by MilovanovMaxim** [MilovanovMaxim/manualBooks#4]

**Comment by MilovanovMaxim** [comment]
1) I will upload the picture
2) you will return picture id
3) I will sent you picture id + user id

можно сделать аватар из ссылки, login уже отдает ссылку на аватар

**Comment by SRobertZ** [comment]
Сделал отображение аватвра из ссылки, присланной сервером
Прикручивание fileupload Буду делать если договримся на 2ю часть.

**Comment by MilovanovMaxim** [comment]
https://slack-files.com/T02J7P39U-F03QEEJHS-7d63ea4c05
разметка модальное окно

**Comment by MilovanovMaxim** [comment]
https://slack-files.com/T02J7P39U-F03QH904H-9cb5bdb6d7
API

**Comment by MilovanovMaxim** [comment]
Go here http://marksmith.biz/mbproject/#/show/user/ and Click to change the picture .

**Comment by MilovanovMaxim** [comment]
```
    var uploader = $scope.uploader = new FileUploader({
        url:  'http://marksmith.biz/uploadtest/upload.php'
    });
```

Скачал https://github.com/nervgh/angular-file-upload поменял URL на их все работает, файл загружается к ним без ошибок

**Comment by MilovanovMaxim** [comment]
https://github.com/nervgh/angular-file-upload/wiki/Module-API тут можно почитать про formData {Array}: Data to be sent along with this file т.е. сразу можно отправить userId

**Comment by MilovanovMaxim** [comment]
uploadPicture() API will accept file and user_id two parameters.

**Comment by SRobertZ** [comment]
Дергаю http://marksmith.biz/uploadtest/upload.php?user_id=40 Файл загружается
приходит ответ File transfer completed
1)Но при последующем логине мне все равно возвращается avatar.jpg,
2)ответ на загрузку должен дать мне название аватара на сервере

**Comment by MilovanovMaxim** [comment]
Рави сказал что все сделал
2) при на попапе надо задать размеры картинке with and hight

**Comment by SRobertZ** [comment]
Рави сделал, но он возвращает адрес картинки равнй id пользователя, а это проблема: браузер кеширует url 40.jpg, пусть он лучше генерит или guid. То есть адрес аватара не должен быть привязан к ид пользователя

**Comment by MilovanovMaxim** [comment]
(function(angular) {
    'use strict';

```
angular.module('mainModule').factory('guid', function() {
    function s4() {
        return Math.floor((1 + Math.random()) * 0x10000)
            .toString(16)
            .substring(1);
    }

    return {

        newGuid: function guid() {
            return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
                s4() + '-' + s4() + s4() + s4();
        }
    };

});
```

})(angular);

Добавь сам гуид к картинке `http://url.com/avatar_Id.jpg?anticashe=newGUID`

**Comment by SRobertZ** [comment]
Это поможет только при смене аватара, но при следующем входе я опять возьму то что пришлет сервер, а при таком подходе при второй смене аватара опять возьмется закешированый при следующем входе.
Я сделал с использованием гуил, но проблема выше остается
