### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by MilovanovMaxim** [MilovanovMaxim/manualBooks#5]
[screen](https://yadi.sk/i/gRGkBcHTeonjT) Waiting API and markup

**Comment by MilovanovMaxim** [comment]
[new API for it](https://slack-files.com/T02J7P39U-F03PFGS0D-72c4254e26)

**Comment by MilovanovMaxim** [comment]
markUp - should change color
color: red; for off
blue for on

**Comment by SRobertZ** [comment]
waiting for markup...

**Comment by MilovanovMaxim** [comment]
Говорит сделай простое модальное окно

**Comment by MilovanovMaxim** [comment]
разметка https://slack-files.com/T02J7P39U-F03QH9ZKM-850569f601

**Comment by MilovanovMaxim** [comment]
Go here http://marksmith.biz/mbproject/#/show/user/ and Click to change the picture .. ive sent you mark-up through skype for ‘change picture’ and ‘change password’
Change Password File:
http://marksmith.biz/mbproject/tpl/modal.changepassword.html
Change Picture File:
http://marksmith.biz/mbproject/tpl/modal.changepicture.html
------------Usage------------
<div class="m-b-md" ng-controller="ModalDemoCtrl">
<script type="text/ng-template" id="myModalContent.html">
<div ng-include="'tpl/modal.changepicture.html'"></div>
</script>

<a class="btn btn-icon btn-rounded btn-info" tooltip="Change Picture" ng-click="open()"><i class="fa fa-file-photo-o m-r-n-xxs"></i></a> 

Other links ...
-------------------------------
