### ISSUE TITLE
Notes implementation

### ISSUE THREAD

**Issue by MilovanovMaxim** [MilovanovMaxim/manualBooks#7]
Waiting for API

**Comment by MilovanovMaxim** [comment]
displayUserNotes() will be implemented 22/02/2014
accepts user_id+website_id
user can remove only last own message

[displayNotes you can find here](https://slack-files.com/T02J7P39U-F03PFNZGM-eb56fdb8c4)

{
    "items": [
        {
            "note_id": "3",
            "note": "hi. welcome",
            "note_by": "ravi vagadiya"
        },
        {
            "note_id": "4",
            "note": "this is nice person",
            "note_by": "ravi vagadiya"
        },
        {
            "note_id": "5",
            "note": "Thanks admin",
            "note_by": "me"
        }
    ],
    "success": "true"
}

it will return name if admin makes note and if user write note on his notes, it will say "me"

**Comment by SRobertZ** [comment]
Еще не хватает времени создания коммента и не ясно для удаления какой метод апи вызывать: deleteUserNote или deleteNote.
А так получение списка сделал

**Comment by MilovanovMaxim** [comment]
deleteUserNote

**Comment by MilovanovMaxim** [comment]
Okay it's done

{
    "items": [
        {
            "note_id": "5",
            "note": "Thanks admin",
            "created": "2015-02-21 12:21:22",
            "note_by": "me"
        },
        {
            "note_id": "4",
            "note": "this is nice person",
            "created": "2015-02-17 05:53:30",
            "note_by": "ravi vagadiya"
        },
        {
            "note_id": "3",
            "note": "hi. welcome",
            "created": "2015-02-17 05:53:21",
            "note_by": "ravi vagadiya"
        }
    ],
    "success": "true"
}

**Comment by MilovanovMaxim** [comment]
Создания заметки нету

**Comment by SRobertZ** [comment]
Потому что заметку может создавать только админ. И мы решали что будем это делать когда будем делать админскую часть.

**Comment by MilovanovMaxim** [comment]
Заметку может создать и пользователь( user can remove only last own message )
{
"note_id": "5",
"note": "Thanks admin",
"created": "2015-02-21 12:21:22",
"note_by": "me"
},
ну ладно раз ты настаиваешь попробую уговорить его, но я слабо в это верю

**Comment by SRobertZ** [comment]
Я сделал добавление и удаление заметок, но АПИ должно: 1) возвращать также удаленые заметки и просто помечать как deleted: true, иначе я всегда смогу удалять послдений коммент.

**Comment by SRobertZ** [comment]
2) апи должно возвращать author_id, иначе я не могу вычислить мой ли это последний коммент

**Comment by MilovanovMaxim** [comment]
можешь, есть слово "me"

**Comment by MilovanovMaxim** [comment]
1) главное чтобы последний был именно свой

**Comment by SRobertZ** [comment]
сервер мне не пресылает note_by: " ". Не могу)) Да и не серъезно проверять так

**Comment by SRobertZ** [comment]
1) главное чтобы последний был именно свой

Представь что я написал несколько последних- удалил последний- опять могу удалить последний и т.д. ТО есть есля я могу удалять все свои последние то ОК. Ладно пусть хотя бы note_by пришлет

**Comment by MilovanovMaxim** [comment]
если приходит "me" то надо подставлять свои имя фамилию, если приходит не me, то берем то что пришло

**Comment by MilovanovMaxim** [comment]
me он починил, оно возвращается

**Comment by SRobertZ** [comment]
Что нужно от Ravi:
1) Чтобы он возвращал список заметок в порядке от старых к новым- сейчас он возвращает от новых к старым. Это приводит к тому что при вставке я должен вставлять в начало списка,а это не очивидно. Особенно если заметок много.
2) Он должен возвращать дату в формате ISO YYYY-MM-DDTHH:mm:ss.sssZ В этом случае я смогу отображать дату которая пришла с сервера и та которая вставлена пользователем в одном часовом поясе

**Comment by MilovanovMaxim** [comment]
Говорит сделал, закрываю?

**Comment by SRobertZ** [comment]
Нет он не сделал- я посмотрел внимательно - у него заметки вообще в разнобой по времени приходят.
